name: Docker Build and Push
description: Build and push Docker image to GHCR with multi-platform support

inputs:
  image-name:
    description: 'Full image name (ghcr.io/org/repo)'
    required: true
  image-tag:
    description: 'Image tag'
    required: true
  push-image:
    description: 'Whether to push the image'
    required: true
  ghcr-username:
    description: 'GHCR username (github.actor)'
    required: true
  ghcr-password:
    description: 'GHCR password (secrets.GITHUB_TOKEN)'
    required: true

runs:
  using: composite
  steps:
    - name: Validate Dockerfile exists
      shell: bash
      run: |
        if [ ! -f "Dockerfile" ]; then
          echo "Error: Dockerfile not found in repository root"
          exit 1
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      if: inputs.push-image == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr-username }}
        password: ${{ inputs.ghcr-password }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ inputs.push-image }}
        tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}
        pull: true
